### ISSUE TITLE
where to initially discuss the variance/bais tradeoff? 

### ISSUE THREAD

**Issue by topepo** [aml4td/website#15]
We'll talk a lot about model complexity in regards to

- the overfitting chapter (e.g. as complexity ☝️, bias 👇) 
- resampling methods
- ensembles
- regression performance (MSE decomposition)
 
Should we have an initial section on it though?

**Comment by jdonland** [comment]
It should be early in the book; probably in Chapter 2.

**Comment by topepo** [comment]
Adding it immediately after basis functions
